### ISSUE TITLE
Question about unequiping trinket

### ISSUE THREAD

**Issue by tantk** [gabrielwong159/MouseHunt#5]
Hi,
Really nice script you have here. I have been using it without much trouble so far. I am a grand duke that just came back from a really long hiatus. Currently in hunting in Lost City for the rainbow map. 

I have just added in some check for lost city
```    
def check_lost_city(self,user_data: dict):
        if self.get_location(user_data) != 'Lost City':
            return
        is_cursed = user_data['quests']['QuestLostCity']['minigame']['is_cursed']
        current_trinket = user_data['trinket_name']
        if is_cursed:
            self.change_trap('trinket', 'searcher_trinket')
            telebot.send_message(f'Curse detected, changing trinket: Searcher Charm')
        elif current_trinket=='Searcher Charm':
            #default as no charm
            self.change_trap('trinket', 'super_cactus_trinket') #<------ no idea how to unequip charm
            telebot.send_message(f'No curse, equip a random charm')
```

How to unequip charm instead of changing charm?

**Comment by gabrielwong159** [comment]
Hey, I'm glad it's going well for you so far. Should have probably created a separate function for it to be clear, but for now you can use
```python3
self.change_trap('trinket', 'disarm')
```

**Comment by tantk** [comment]
something went wrong lol. i'll just select some charm that i have no use of for now...
```cannot find trinket: disarm```

edited:
loosen the checks for the change trap function and it works now. thx!

**Comment by gabrielwong159** [comment]
Sorry about that, forgot to account for that line of code. Have indeed loosened the checks for `disarm` and pushed a new commit.
